In [1]:
import numpy as np

In [2]:
bases_rec = np.array([5,2,4,7,8])
alturas_rec = np.array([3,4,1,4,3])

In [3]:
area_rec = bases_rec*alturas_rec

In [4]:
area_rec

array([15,  8,  4, 28, 24])

In [5]:
area_rec[area_rec>10]

array([15, 28, 24])

In [6]:
a = [2, 5, 7]
b = [5, 6, 3]

In [7]:
a + b

[2, 5, 7, 5, 6, 3]

In [8]:
a = np.array([2, 5, 7])
b = np.array([5, 6, 3])

In [9]:
a + b

array([ 7, 11, 10])